### ISSUE TITLE
Suggested host header injection mitigation does not seem to be working

### ISSUE THREAD

**Issue by jdleesmiller** [ankane/secure_rails#4]
Since I opened https://github.com/rails/rails/issues/29893, I thought I should also mention here that I tried the suggested mitigation:

- Prevent [host header injection](http://carlos.bueno.org/2008/06/host-header-injection.html) - add the following to `config/environments/production.rb`

  ```ruby
  config.action_controller.default_url_options = {host: "www.yoursite.com"}
  config.action_controller.asset_host = "www.yoursite.com"
  ```

on on a rails 5.1.2 application, and it did not seem to work. Please see the details on https://github.com/rails/rails/issues/29893 for more info on the test I ran and an alternative mitigation.

If it's definitely working for you, it would be great if you could mention that on the rails issue.

**Comment by ankane** [comment]
Hey @jdleesmiller, thanks for reporting 👍  I commented on the Rails issue, but also wanted to comment here. The mitigation technique in this repo does prevent cache poisoning in views. Try rendering `root_url`. It does look like open redirects are still possible if you use `redirect_to some_path` rather than `redirect_to some_url`, which needs a fix.

**Comment by ankane** [comment]
Actually, the redirect issue shouldn't be harmful, so not sure there's an issue. Going to close for now, but feel free to continue the conversation if you have additional thoughts.

**Comment by jdleesmiller** [comment]
For completeness: as noted in https://github.com/rails/rails/issues/29893#issuecomment-319768403, you're right that this does bring `root_url` back under the application's control. (But `request.host` is still under the attacker's control.)

The open redirect issue does seem less worrying. AFAICT it requires the attacker to get a downstream cache to cache the redirect, which is apparently possible, if I am reading https://hackerone.com/reports/487 correctly (there they escaped the issue, but it was a 'near miss').

Thanks again for your time on this!
