### ISSUE TITLE
Cache-Control headers

### ISSUE THREAD

**Issue by cjbarnaby** [ankane/secure_rails#9]
Query re: [Browser Caching](https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/http/cache.rb#L185), specifically: 
> response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"

It seems that — [since Rails 5.2](https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/http/cache.rb#L185) — `cache-control` headers are normalized in a way that means `must-revalidate` and `max-age=0` will get stripped when used in conjunction with `no-cache` and `no-store`. See also [this Issue on the Rails repo](https://github.com/rails/rails/issues/32557).

**Comment by ankane** [comment]
Thanks @cjbarnaby! I've updated the guide to use the normalized header to avoid confusion.
